// svelte/src/lib/pages/Landing.svelte
<script lang="ts">
    import { Col, Container, Row } from "sveltestrap";
    import hero from "../../assets/hero-img.png";
    import comment from "../../assets/works/a-comment.svg";
    import wallet from "../../assets/works/a-wallet.svg";
    import yields from "../../assets/works/a-yield.svg";
    import CreatorCard from "../components/CreatorCard.svelte";
    import { fetchCreators } from "../utils/fetch";

    const creators = fetchCreators();
</script>

<section class="background" id="landing">
    <Container style="min-width: 90%; max-height: 680px">
        <Row class="d-flex flex-wrap align-items-center justify-content-center">
            <Col>
                <div class="row-container">
                    <h1 class="title">
                        Stake your assets, support the creator with the yield.
                    </h1>
                </div>
            </Col>
            <Col>
                <div class="row-container">
                    <div class="logo">
                        <img class="logo" src={hero} alt="hero" width="480px" />
                    </div>
                </div>
            </Col>
        </Row>
    </Container>
</section>
<section class="works">
    <Container>
        <h1 class="work-title">How it Works?</h1>
        <Row>
            <Col>
                <img src={wallet} alt="wallet" width="120px" />
                <p class="work-detail">
                    Connect Wallet and <u><b>find creator to support</b></u>
                </p>
            </Col>
            <Col>
                <img src={yields} alt="yield" width="120px" />
                <p class="work-detail">
                    Stake assets in smart contract.
                    <br />
                    <u><b>Asset's yields are sent to creator</b></u>
                    <br />
                    <u><b>Withdrawl anytime!</b></u>
                </p>
            </Col>
            <Col>
                <img src={comment} alt="comment" width="120px" />
                <p class="work-detail">
                    Leave a <u><b>motivational comment</b></u> for your creator
                </p>
            </Col>
        </Row>
    </Container>
</section>
<section class="creators">
    <Container>
        <h1>Featured Creators</h1>
        {#await creators}
            <h5>Loading</h5>
        {:then crts}
            <Row>
                {#each crts as creator}
                    <Col md={4}>
                        <CreatorCard {creator} />
                    </Col>
                {/each}
            </Row>
        {/await}
    </Container>
</section>

<style>
    .background {
        min-height: 70vh;
        max-height: 680px;
        padding-top: 60px;
        background: rgba(0, 0, 0, 0)
            linear-gradient(
                rgb(71, 145, 209) 16.51%,
                rgb(71, 145, 209) 54.62%,
                rgb(34, 86, 131) 77.38%
            )
            repeat scroll 0% 0%;
        overflow: hidden;
        color: white;
    }

    .title {
        padding: 1.5rem;
        margin-left: 15%;
        font-size: 2.8rem;
        font-weight: 700;
        text-align: left;
        width: 512px;
        line-height: 1.5;
    }

    .row-container {
        justify-content: center;
    }

    img.logo {
        margin-left: auto;
        margin-right: auto;
        display: block;
    }

    .works {
        background-color: rgb(243, 243, 243);
        padding: 3rem 0;
    }

    .work-title {
        color: rgb(71, 145, 209);
    }

    .work-detail {
        font-size: 20px;
        margin-top: 20px;
    }

    .creators {
        padding: 3rem 0;
    }
</style>

// client/src/views/User/Landing.jsx
import React, { useEffect } from "react";
import Header from "../../components/Header";
import { Box, SimpleGrid, Image, Center, Text, Container, Button, HStack } from '@chakra-ui/react';
import { useState } from "react";
import axios from 'axios';
import { serverUrl } from "../../services/serverUrl";
import Footer from "../../components/Footer";
import { NavLink } from "react-router-dom";


const Landing = () => {
    const [creators, setCreators] = useState([])

    useEffect(() => {
        try {
            axios.get(`${serverUrl}listCreators`)
            .then((response) => {
                console.log(response.data);
                setCreators(response.data)
            });
        } catch (error) {
            console.log(error)
        }
    }, [])

    return (
        <>  
            <Header optionToCreate={true}/>
            <SimpleGrid columns={{ base: 1, md: 2 }} pb={4} style={{background: "linear-gradient(180deg, #4791D1 16.51%, #4791D1 54.62%, #225683 77.38%)", overflow: "hidden"}}>
                <Container maxW='lg' style={{width: "100%", padding: "200px 0"}}>
                    <Text p={6} fontSize='5xl' fontWeight='bold' color='#fff'>
                        Stake your assets, support the creator with the yield.
                    </Text>
                </Container>

                <Container maxW='lg' style={{width: "100%", position: "relative", top: "0", left: "-120px"}}>
                    <Image
                        mb={4}
                        src='hero-img.png'
                        fallbackSrc='hero-img.png'
                        style={{width: "1000px", height: "auto", position: "relative", top: "120px"}}
                    />
                </Container>
            </SimpleGrid>

            <Box bgColor='#f3f3f3'>
                <Container
                    p={6}
                    maxW='lg'
                    color='#4791D1'
                    fontSize='4xl'
                    fontWeight='bold'
                    centerContent
                >
                    How it Works?
                </Container>
                <Container maxW='6xl' p={6}>
                    <SimpleGrid columns={{ base: 1, md: 3 }} mb={4}>
                        <Container maxW='sm' centerContent>
                            <Image
                                mb={4}
                                src='a-wallet.svg'
                                fallbackSrc='a-wallet.svg'
                                borderRadius='full'
                                style={{width: "120px", marginBottom: "20px"}}
                            />
                            <HStack fontSize='xl'>
                                {/* <Text mr={6}>1)</Text> */}
                                <Text>Connect Wallet and <Text as='u' fontWeight='semibold'>find creator to support</Text></Text>
                            </HStack>
                        </Container>
                        <Container maxW='sm' centerContent>
                            <Image
                                mb={4}
                                src='a-yield.svg'
                                fallbackSrc='a-yield.svg'
                                borderRadius='full'
                                style={{width: "120px", marginBottom: "20px"}}
                            />
                            <HStack fontSize='xl'>
                                <Text>
                                    Stake assets in smart contract. <Text as='u' fontWeight='bold'>Asset’s yields are sent to creator</Text>
                                    <br/><br/>
                                    <Text as='u' fontWeight='bold'>Withdrawl anytime!</Text>
                                </Text>
                            </HStack>
                        </Container>
                        <Container maxW='sm' centerContent>
                            <Image
                                mb={4}
                                src='a-comment.svg'
                                fallbackSrc='a-comment.svg'
                                borderRadius='full'
                                style={{width: "120px", marginBottom: "20px"}}
                            />
                            <HStack fontSize='xl'>
                                <Text>
                                    Leave a <Text as='u' fontWeight='bold'>motivational comment</Text> for your creator
                                </Text>
                            </HStack>
                        </Container>
                    </SimpleGrid>
                </Container>
            </Box>

            <Box>
                <Container
                    p={6}
                    maxW='lg'
                    fontSize='4xl'
                    fontWeight='bold'
                    centerContent
                >
                    Featured Creators
                </Container>
                <Container maxW='6xl' p={6} mb={6}>
                    <SimpleGrid columns={{ base: 1, md: 3 }} mb={4} spacing={4}>
                        {creators.map((creator, i) => {
                            return (
                                <Container
                                maxW='sm'
                                border='solid 2px #f3f3f3'
                                borderRadius='lg'
                                key={`${i}`}
                            >
                                <Box
                                    pt={3}
                                    maxW='lg'
                                    color='#4791D1'
                                    fontSize='md'
                                    fontWeight='semibold'
                                >
                                    ❤️ 200 Supporters
                                </Box>
                                <Center p={6}>
                                    <Image
                                        borderRadius='full'
                                        boxSize='170px'
                                        src={creator.photo}
                                        alt={creator.name}
                                    />
                                </Center>
                                <Box align='center' mb={4}>
                                    <Text fontSize='2xl' fontWeight='bold' as='u'>{creator.name}</Text>
                                    <Text fontSize='md'>{creator.tagline}</Text>
                                    <Button
                                        mt={10}
                                        bgColor='#4791D1'
                                        color='#fff'
                                        size='lg'
                                    >
                                        <NavLink to={`/detailView/${creator.address}`}>
                                            View Creator
                                        </NavLink>
                                    </Button>
                                </Box>
                            </Container>
                            )
                        })}
                    </SimpleGrid>
                </Container>
            </Box>
            <Footer/>
        </>
    );
}

export default Landing;
